### PR TITLE
Fix ScriptMonkeyClassLoader for IDEA 15 EAP

### PR DESCRIPTION
**Pull request by vsch**
Hi Siddique,

I have wanted to play with this plugin for almost a year, but every time I tried it would not work on my version of IDEA. When I released my own plugin [MultiMarkdown](https://plugins.jetbrains.com/plugin?pr=&pluginId=7896) and felt comfortable looking at plugin code I decided to dive in and see if I can make it work, now on IDEA 15 EAP community edition. I succeeded but please double check my changes since I am far from a Java expert and my tests were limited to IDEA 14 community edition branch 141 and IDEA 15 EAP.

The big changes were to the ScriptMonkeyClassLoader. The methods used in it were marked deprecated and to be removed in IDEA 15, which has happened. I changed the class to delegate to instead of extend UrlClassLoader and create a new delegate when URL's are added. Seems to work. and I can finally play with JavaScript.

I also added the .iml file which is needed for the project build. Your .gitignore had this file excluded but without it, it is a pain because anyone forking it has to figure out how to setup the project and module dependencies. I solved the problem by creating a new plug-in project and modified it so I can build and test the plugin. You may want to commit your version of the .iml file over mine.

The rest of the changes are IDEA's import optimization and auto formatting changes.

I am planning on writing a library of text editing functions so that I can quickly throw together a custom action instead of typing away like I am back in the 80's (yes I am old enough to have been there :) ). I find IDEA is great for code refactoring when it is implemented but for raw text manipulation it falls far short of dumb text editors. I would like to fix this, even if it is just for me. I find myself switching out of it to my old work horse editor for bulk text manipulations.

Thank you for the plugin, and if you haven't given up on it and want to collaborate on making improvements I would be willing. I think there were a lot of people who tried it but it did not work for them so they just gave up and uninstalled it. I think it has great potential.

Vladimir.

### CODE REVIEW

**Comment by siddii** [comment]
Awesome... I appreciate your effort!

I may not have time to test these changes at this moment. If you are confident, I can merge those changes.

**Comment by siddii** [comment]
To make things easier... I am making you a collaborator for this project. Sounds good?

**Comment by vsch** [comment]
Thank you for the trust. The changes I made work but I will use it for a couple of days to see if it breaks under some conditions. I am not familiar enough with the implementation to have a good model of its dynamic behavior.

The changes require updating `augmentedClassLoader` in `Thread.currentThread().setContextClassLoader(augmentedClassLoader)` to be changed every time a library is added to by the script. I don't think this is done dynamically after creating the script engine but cannot be 100% certain. This is the only place where the old code and the new one are not compatible.

I'll play with it a bit more and add the new version 1.1.1 to the dist.  I think issue #6 would be addressed by this fix. I'll comment on it and ask if he can download the new build and try it out. If it works for him I'll merge the PR.

I'll keep you posted on the progress and look forward to spicing up the plugin with a few must have features so that it gets the attention that I think it deserves.

**Comment by siddii** [comment]
Absolutely... please go for it :+1:

**Comment by vsch** [comment]
@siddii, I have been hacking away at the source and have made some progress. The nashorn engine has some differences from rhino that I am still trying to absorb but I got the timebar.js working. I love it.

I made a change in the JS Shell pane. I changed the code to use a Standard IntelliJ Editor and set it to JavaScript syntax highlighting. Not all the quirks are out but it is more comfortable for playing around. You get the keymap that you are used to and fancy edit functions. I hacked the error reporting too so that it reports the right line number since I enabled gutter line numbers. I'll be doing more learning and clean up before committing but here is a screenshot in case you are curious:

screen shot 2015-09-03 at 4 00 44 am

**Comment by siddii** [comment]
Awesome! Feel free to merge it to master whenever you are ready.

**Comment by vsch** [comment]
merged into develop branch.

**Pull request closed without merging**
